export const LOOPBACK_ADDRESS = '127.0.0.1';
export const IP_F_INET_ADDR = 'IP_F_INET_ADDR';
export const IFCONFIG = 'IFCONFIG';
export const STORE_REF_PACKAGE = 'ADBB_SESSION_PACKAGE';
export const STORE_LAST_PKG_NOTICE_TIME = 'ADBB_LAST_PKG_NOTICE_TIME';